# docker-compose.yml
version: '3.8'

volumes:
  productdb_vol:

networks:
  micro_network:
    external:
      name: micro_network

services:
  product-api:
    container_name: cproduct-service
    build:
      context: .
    ports:
      - "5002:5002"
    depends_on:
      - product-db
    networks:
      - micro_network
    restart: always

  product-db:
    container_name: cproduct_dbase
    image: postgres:latest
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: postgres2
      POSTGRES_PASSWORD: Mango43
      POSTGRES_DB: product
    networks:
      - micro_network
    volumes:
    - productdb_vol:/var/lib/postgresql/data
    - ./initdb-product.sql:/docker-entrypoint-initdb.d/initdb-product.sql
